# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        name: "install app"
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm test
        services: 
          - mongo 
#    - step:
#        name: "build artifact"
#        caches:
#            - node
#        script:
#          - apt-get update
#          - apt-get install zip
#          - zip backend-nodejs.zip -r ./*
#        # Define an artifact to pass the zip file to the next step
#        artifacts: 
#          - backend-nodejs.zip
#    - step:
#        name: "Deploy to Production"
#        # Track production environments builds using deployments.
#        deployment: production
#        script:
#        - pipe: atlassian/aws-elasticbeanstalk-deploy:0.5.0
#          variables:
#            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
#            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
#            AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
#            APPLICATION_NAME: $APPLICATION_NAME
#            ENVIRONMENT_NAME: $ENVIRONMENT_NAME
#            ZIP_FILE: "backend-nodejs.zip"
#            S3_BUCKET: $S3_BUCKET

definitions: 
  services: 
    mongo: 
      image: mongo