version: '3.4'

services:

  node:
    build:
      context: .
      dockerfile: node.dockerfile
    ports:
      - "3000:3000"
    networks:
      - nodeapp-network
    depends_on: 
      - mongodb
      
  mongodb:
    container_name: mongo
    image: mongo
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge